/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Window-Style.h
 #	source generated by 4D Plugin Wizard
 #	Project : Window Style
 #	author : miyako
 #	2021/04/23
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_WINDOW_STYLE_H
#define PLUGIN_WINDOW_STYLE_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#endif

#pragma mark -

static void SET_WINDOW_STYLE(PA_PluginParameters params);

#endif /* PLUGIN_WINDOW_STYLE_H */
